### PR TITLE
Fixed boolean test in conditional fields.

### PR DESCRIPTION
**Pull request by paulmassen**

### CODE REVIEW

**Comment by paulmassen** [comment]
I forgot to mention that this fix fixes a problem on conditional fields. The new updates makes the fields under conditional to be displayed no matter what the result of the evaluate condition is.

**Comment by rhukster** [comment]
Can you provide me with your form definition where conditional field is failing ? I'm using it for the displaying the 2fa field in admin and it's working fine as is.

**Comment by paulmassen** [comment]
Sure, I used it in my seo plugin, here is an example.
The fields are displayed/not displayed depending on the plugin configuration but it has stopped working after last update.
https://github.com/paulmassen/grav-plugin-seo/blob/master/blueprints/seo.yaml#L104

**Comment by rhukster** [comment]
This actually breaks the simplified conditional format i created.. So i've fixed both in my https://github.com/getgrav/grav-plugin-form/commit/0105caebdcb8580154725327ddbc9a6f2115ca21 commit.

**Comment by rhukster** [comment]
BTW to test:

```
    condition-1:
      type: conditional
      condition: config.plugins.admin.twofa_enabled

      fields:
       spacer-1:
          type: spacer
          text: Conditional Style 1

    condition-2:
        type: conditional
        condition: "config.plugins.admin.twofa_enabled ? 'true' : 'false'"

        fields:
         spacer-2:
            type: spacer
            text: Conditional Style 2
```

**Pull request closed without merging**
