### PR TITLE
Feature: Server side validation

### PR DESCRIPTION
**Pull request by Sommerregen**
This PR adds full server-side validation support for forms using Grav built-in internals (`Validation` class!) via blueprints and cleans up the code a bit.

**EDIT:** ~~Please do not merge yet! I have some minor tweaks, I would like to add. In the meantime feel free to comment on the code.~~

Ok, ready to be merged! :grinning:

### CODE REVIEW

**Comment by flaviocopes** [comment]
:+1: ! Will test tomorrow :)

**Comment by Sommerregen** [comment]
Ah, cool! :sunny:

**Comment by flaviocopes** [comment]
Was testing the PR, the Comments and Guestbook forms (generated and processed using the Form plugin) submits do not work any more by switching the Form plugin branch to the PR branch.

screen shot 2015-10-27 at 15 11 58

Do you have an idea of what of the changes could be the problem?

**Comment by Sommerregen** [comment]
@flaviocopes Currently not. But I guess it has something to do with the hidden form elements for example in the **Comments** plugin, https://github.com/getgrav/grav-plugin-comments/blob/develop/comments.yaml#L37-L52 . Since there is no `label` field it throws an error.

Gotcha! The validation class has to be fixed, try change the error line to

```php
$name = ucfirst(isset($field['label']) ? $field['label'] : $field['name']);
```

**Comment by flaviocopes** [comment]
Ah that might be the thing. I'll try :)

**Comment by flaviocopes** [comment]
Added the Grav check and merged, tested with Comments and Guestbook, works fine!

**Pull request merged**
