### PR TITLE
fixed capitlisation on form class link

### PR DESCRIPTION
**Pull request by charlesrt**
Pages containing forms were failing. Changing the capitalisation for the file link fixed it.

### CODE REVIEW

**Comment by rhukster** [comment]
was just going to fix this!

**Comment by rhukster** [comment]
thanks! will re-release

**Comment by charlesrt** [comment]
Anytime. I just had a major meltdown when it stopped working. Glad it was something simple 👍

**Comment by rhukster** [comment]
1.2.2 released and GPM updated.  Thanks again.

**Pull request merged**
