### PR TITLE
Escape YAML to form save action to prevent parsing errors

### PR DESCRIPTION
**Pull request by hughbris**
resolves issue #205

### CODE REVIEW

**Comment by rhukster** [comment]
Do you have some sample form+data so i can quickly test/confirm this fix?

**Comment by hughbris** [comment]
Here's the basic test form page I was using on top of grav-admin + data manager install. Unpack into user/pages and access from /forms/test:

[02-forms.tar.gz](https://github.com/getgrav/grav-plugin-form/files/1444412/02-forms.tar.gz)

Complete textarea field with newline, then try to view using Data Manager. You'll have to fix or remove the broken files saved before you can compare after patching.

**Comment by hughbris** [comment]
Updated with another commit as I realised I may have broken iterable item encoding (JSON), which I did :/

Test this by adding this field to the samepl form provided above in tarball:
```yaml
            - name: how-hear
              label: 'How did you hear about us?'
              type: checkboxes
              options:
                word: Friend or word of mouth
                dentist: Referral
                yellow-pages: Yellow Pages
                search: Online search (Google etc.)
                social-media: Social media
                other: Other
              use: keys
```

**Comment by hughbris** [comment]
Thanks @rhukster - you raise a good issue that it would be handy to have a fully featured reference form for testing PRs etc. Seems to me this plugin is very prone to regressions.

**Pull request merged**
